#pragma once
#include <string>

enum class TokenType {
  FN, RETURN, IF, ELSE, WHILE, FOR, BREAK, CONTINUE, LET, EXTERN,
  INT_KW, CHAR_KW, BOOL_KW, STR_KW, VOID_KW, TRUE_KW, FALSE_KW, SIZEOF,

  IDENTIFIER, INTEGER, STRING,

  PLUS, MINUS, STAR, SLASH, PERCENT,
  PLUS_PLUS, MINUS_MINUS,
  PLUS_EQUAL, MINUS_EQUAL, STAR_EQUAL, SLASH_EQUAL,
  EQUAL, EQUAL_EQUAL, BANG, BANG_EQUAL,
  LESS, LESS_EQUAL, GREATER, GREATER_EQUAL,
  AMPERSAND, PIPE, TILDE,

  LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, SEMICOLON, COMMA, COLON, ARROW, DOT,

  COMMENT, END, UNKNOWN
};

struct Token {
  TokenType type;
  std::string lexeme;
  size_t line;
  size_t col;
};
